### ISSUE TITLE
Some buttons do not work in specific scenarios

### ISSUE THREAD

**Issue by EmmaKnijn** [MasonGulu/cc-giim#1]
Pressing home does not return to the beginning of the line, also, typing whitespace and trying to delete it with delete or backspace does nothing

**Comment by ShreksHellraiser** [comment]
Home has been added as a keybind to take you to X=1 (regardless of position in document). We discussed on discord about the delete/backspace behavior, it doesn't shift text when you delete and that's intentional due to the image editing features, I may add controls for shifting lines in the future.
